title: Li Yucang
SEOTitle: 李宇仓 | Li Yucang
header-img: img/bg/home-bg.jpg
email: 765313580@qq.com
description: "李宇仓的博客"
keyword: "李宇仓, Li Yucang, Yucang, liyucang, 李宇仓的博客, js, web"
url: "https://liyucang-git.github.io" # 博客url
baseurl: "" # 博客的基本路径，比如：在'host/blog'下，则填'/blog'
github_repo: "https://github.com/liyucang-git/liyucang-git.github.io.git" # 博客代码的地址

sidebar: true # 是否显示侧边栏
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/site/about-BY-gentle.png # 使用绝对路径

zhihu_username: xiang-cai-rou-jia-mo
github_username: liyucang-git
twitter_username: lalalaaalaala
# weibo_username: liyucang
# facebook_username: liyucang
# jianshu_username: liyucang

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM  # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true # 是否开启Gitalk评论
  clientID: 06ecd1f17737cb6381b3 # 生成的clientID
  clientSecret: a5abebef65db1c0f5bb62895c757ba369e10b921 # 生成的clientSecret
  repo: liyucang-git.github.io # 仓库名称
  owner: liyucang-git # github用户名
  admin: liyucang-git # 管理员
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩

# 百度统计
ba_track_id: 039819f73ddbdc03f2c9139a748a309f

# Google统计
ga_track_id: 'UA-135991629-1' # Format: UA-xxxxxx-xx
ga_domain: auto # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true # 是否使用首页标签
featured-condition-size: 0 # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false

# 友情连接
friends: [
    # {
    #     title: "Apple Developer",
    #     href: "https://developer.apple.com/"
    # }
]
